More options in ethd prune-history

diff --git a/ethd b/ethd
--- a/ethd
+++ b/ethd
@@ -998,7 +998,7 @@ Full\". Free space:"
 
   if [[ "${low}" -eq 1 && "${NETWORK}" = "mainnet" ]]; then
 #shellcheck disable=SC2154
-    if [[ "${EL_NODE_TYPE}" =~ ^(pre-merge-expiry|aggressive-expiry|rolling-expiry)$ ]]; then
+    if [[ "${EL_NODE_TYPE}" =~ expiry ]]; then
       echo "You are already configured to expire execution layer history."
     else
       echo "You are not configured to expire execution layer history. You can free space with \"${__me} prune-history\"."
@@ -2820,6 +2820,15 @@ prune-history() {
   local prune_marker
   local warning
   local yn
+  local choices
+  local num_items
+  local menu_height
+  local target
+  local target_level
+  local current_level
+  local must_resync
+
+  target=""
 
   while :
   do
@@ -2831,12 +2840,49 @@ prune-history() {
         __non_interactive=1
         shift
         ;;
+      --pre-merge)
+        if [[ -n "${target}" ]]; then
+          echo "Only one history expiry mode can be specified, and you already have ${target}."
+          echo "Aborting."
+          exit 1
+        fi
+        target=pre-merge
+        shift
+        ;;
+      --pre-cancun)
+        if [[ -n "${target}" ]]; then
+          echo "Only one history expiry mode can be specified, and you already have ${target}."
+          echo "Aborting."
+          exit 1
+        fi
+        target=pre-cancun
+        shift
+        ;;
+      --rolling)
+        if [[ -n "${target}" ]]; then
+          echo "Only one history expiry mode can be specified, and you already have ${target}."
+          echo "Aborting."
+          exit 1
+        fi
+        target=rolling
+        shift
+        ;;
+      --aggressive)
+        if [[ -n "${target}" ]]; then
+          echo "Only one history expiry mode can be specified, and you already have ${target}."
+          echo "Aborting."
+          exit 1
+        fi
+        target=aggressive
+        shift
+        ;;
       *)
         echo "Error: Unknown option: $1" >&2
         exit 1
         ;;
     esac
   done
+
   if [[ "${ETHD_FRONTEND:-}" = "noninteractive" ]]; then
     __non_interactive=1
   fi
@@ -2846,73 +2892,212 @@ prune-history() {
     exit 1
   fi
 
-# Only PoW right now, which is mainnet or sepolia
+# pre-cancun and pre-merge are only meaningful on mainnet or sepolia
   var=NETWORK
   __get_value_from_env "${var}" "${__env_file}" "__value"
-  if [[ ! "${__value}" =~ ^(mainnet|sepolia)$ ]]; then
-    echo "There is no pre-merge history for ${__value} network."
+  if [[ "${target}" =~ ^(pre-merge|pre-cancun)$ && ! "${__value}" =~ ^(mainnet|sepolia)$ ]]; then
+    echo "There is no ${target} history for ${__value} network."
     echo "Nothing to do. Aborting."
     exit 0
   fi
 
 # Check whether this has already been done
   var=EL_NODE_TYPE
-  __get_value_from_env "${var}" "${__env_file}" "__value"
-  if [[ "${__value}" =~ ^(pre-merge-expiry|aggressive-expiry|rolling-expiry)$ ]]; then
-    echo "This node is already configured for \"${var}=${__value}\"."
+  __get_value_from_env "${var}" "${__env_file}" "EL_NODE_TYPE"
+  if [[ "${EL_NODE_TYPE}" = "${target}-expiry" ]]; then
+    echo "This node is already configured for \"${var}=${EL_NODE_TYPE}\"."
     echo "Nothing to do. Aborting."
     exit 0
   fi
-  if [[ "${__value}" = "archive" ]]; then
+  if [[ "${EL_NODE_TYPE}" = "archive" ]]; then
     echo "This node is an archive node, and should not use expired history."
     echo "Nothing to do. Aborting."
     exit 0
   fi
 
   var="COMPOSE_FILE"
-  __get_value_from_env "${var}" "${__env_file}" "__value"
-  case "${__value}" in
+  __get_value_from_env "${var}" "${__env_file}" "COMPOSE_FILE"
+
+  if [[ -z "${target}" ]]; then
+    if [[ "${__non_interactive}" -eq 1 ]]; then
+      echo "You need to specify a pruning mode when running in non-interactive mode."
+      echo "Aborting."
+      exit 1
+    fi
+
+    choices=()
+
+    choices+=("pre-merge" "Pre-merge expiry")
+
+    case "${COMPOSE_FILE}" in
+      *besu.yml*)
+        choices+=("rolling" "Rolling expiry (experimental)")
+        choices+=("aggressive" "Aggressive expiry (experimental)")
+        ;;
+      *erigon.yml*)
+        choices+=("rolling" "Rolling expiry")
+        choices+=("aggressive" "Aggressive expiry")
+        ;;
+      *nethermind.yml*)
+        choices+=("pre-cancun" "Pre-Cancun expiry")
+        choices+=("rolling" "Rolling expiry (experimental)")
+        ;;
+      *reth.yml*)
+        choices+=("pre-cancun" "Pre-Cancun expiry")
+        choices+=("rolling" "Rolling expiry")
+        choices+=("aggressive" "Aggressive expiry")
+        ;;
+    esac
+
+    num_items=$(( ${#choices[@]} / 2 ))
+    menu_height=$(( 8 + num_items ))
+
+    target=$(whiptail --notags --title "Select history expiry extent" --menu \
+    "How much history do you wish to prune?" "${menu_height}" 65 "${num_items}" \
+    "${choices[@]}" 3>&1 1>&2 2>&3)
+  fi
+
+  case "${target}" in
+    pre-merge)
+      target_level=1
+      ;;
+    pre-cancun)
+      target_level=2
+      ;;
+    rolling)
+      target_level=3
+      ;;
+    aggressive)
+      target_level=4
+      ;;
+    *)
+      echo "Unable to parse ${target} expiry. This is a bug. Aborting"
+      exit 70
+      ;;
+  esac
+
+  case "${EL_NODE_TYPE}" in
+    full)
+      current_level=0
+      ;;
+    pre-merge-expiry)
+      current_level=1
+      ;;
+    pre-cancun-expiry)
+      current_level=2
+      ;;
+    rolling-expiry)
+      current_level=3
+      ;;
+    aggressive-expiry)
+      current_level=4
+      ;;
+    *)
+      echo "Unable to parse node type ${EL_NODE_TYPE}. This is a bug. Aborting"
+      exit 70
+      ;;
+  esac
+
+# Some clients support changing history expiry without resync. This can only ever throw away more history.
+# If the user wants more history now, that requires a resync
+  if [[ "${target_level}" -lt "${current_level}" ]]; then
+    must_resync=1
+  else
+    must_resync=0
+  fi
+
+  case "${COMPOSE_FILE}" in
     *geth.yml*)
       client="Geth"
+      if [[ "${target}" =~ ^(pre-cancun|rolling|aggressive)$ ]]; then
+        echo "${target} expiry is not supported by ${client}, or ${__project_name} doesn't know how to configure it."
+        echo "Aborting."
+        exit 1
+      fi
       min_ver="v1.16.0"
-      extra_msg="Pre-merge history can be pruned by Geth without requiring a full resync. You can observe pruning with \"./ethd logs -f execution\"."
-      prune_marker="/var/lib/geth/prune-marker"
+      if [[ "${must_resync}" -eq 0 ]]; then
+        extra_msg="History can be pruned by Geth without requiring a full resync. You can observe pruning with \"./ethd logs -f execution\"."
+        prune_marker="/var/lib/geth/prune-marker"
+      else
+        extra_msg="To move from ${EL_NODE_TYPE} to ${target} expiry requires a full resync, which should take 6-8 hours.\nYou can use https://rescuenode.com to keep attesting during resync."
+        prune_marker=""
+      fi
       ;;
     *nimbus-el.yml*)
       client="Nimbus"
+      if [[ "${target}" =~ ^(pre-cancun|rolling|aggressive)$ ]]; then
+        echo "${target} expiry is not supported by ${client}, or ${__project_name} doesn't know how to configure it."
+        echo "Aborting."
+        exit 1
+      fi
       min_ver="v0.10.0"
-      extra_msg="To prune pre-merge history, a full resync is required, which should take 5 days.\nYou can use https://rescuenode.com to keep attesting during resync."
+      extra_msg="To switch to ${target} expiry requires a full resync, which should take 5 days.\nYou can use https://rescuenode.com to keep attesting during resync."
       prune_marker=""
       ;;
     *nethermind.yml*)
       client="Nethermind"
+      if [[ "${target}" =~ ^(aggressive)$ ]]; then
+        echo "${target} expiry is not supported by ${client}, or ${__project_name} doesn't know how to configure it."
+        echo "Aborting."
+        exit 1
+      fi
       min_ver="v1.35.2"
-      extra_msg="Pruning pre-merge history does not require a resync and should be immediate."
-      prune_marker="/var/lib/nethermind/minimal-node"
+      if [[ "${must_resync}" -eq 0 ]]; then
+        extra_msg="${target} expiry does not require a resync and should be immediate."
+        prune_marker="/var/lib/nethermind/minimal-node"
+      else
+        extra_msg="To move from ${EL_NODE_TYPE} to ${target} expiry requires a full resync, which should take 1-2 hours.\nYou can use https://rescuenode.com to keep attesting during resync."
+        prune_marker=""
+      fi
       ;;
     *besu.yml*)
       client="Besu"
+      if [[ "${target}" =~ ^(pre-cancun)$ ]]; then
+        echo "${target} expiry is not supported by ${client}, or ${__project_name} doesn't know how to configure it."
+        echo "Aborting."
+        exit 1
+      fi
       min_ver="25.11.0"
-      extra_msg="To prune pre-merge history, a full resync is required, which should take 16-24 hours.\nYou can use https://rescuenode.com to keep attesting during resync."
+      extra_msg="To switch to ${target} expiry requires a full resync, which should take 16-24 hours.\nYou can use https://rescuenode.com to keep attesting during resync."
       prune_marker=""
       ;;
     *reth.yml*)
       client="Reth"
       min_ver="v1.8.0"
-      extra_msg="Pruning pre-merge history does not require a resync and should be immediate.\nA resync saves more space than a prune: You can set \"EL_NODE_TYPE=pre-merge-expiry\" manually with \"nano .env\" and then resync with \"./ethd resync-execution\"."
-      prune_marker="/var/lib/reth/minimal-node"
+      if [[ "${must_resync}" -eq 0 ]]; then
+        extra_msg="${target} expiry does not require a resync and should be immediate.\nA resync saves more space than a prune: You can set \"EL_NODE_TYPE=${target}-expiry\" manually with \"nano .env\" and then resync with \"./ethd resync-execution\"."
+        prune_marker="/var/lib/reth/minimal-node"
+      else
+        extra_msg="To move from ${EL_NODE_TYPE} to ${target} expiry requires a full resync, which should take 1-2 hours.\nYou can use https://rescuenode.com to keep attesting during resync."
+        prune_marker=""
+      fi
       ;;
     *erigon.yml*)
       client="Erigon"
+      if [[ "${target}" =~ ^(pre-cancun)$ ]]; then
+        echo "${target} expiry is not supported by ${client}, or ${__project_name} doesn't know how to configure it."
+        echo "Aborting."
+        exit 1
+      fi
       min_ver="v3.0.12"
-      extra_msg="To prune pre-merge history, a full resync is required, which should take 2-3 hours.\nYou can use https://rescuenode.com to keep attesting during resync."
+      extra_msg="To switch to ${target} expiry requires a full resync, which should take 2-3 hours.\nYou can use https://rescuenode.com to keep attesting during resync."
       prune_marker=""
       ;;
     *ethrex.yml*)
       client="Ethrex"
+      if [[ "${target}" =~ ^(pre-cancun|rolling|aggressive)$ ]]; then
+        echo "${target} expiry is not supported by ${client}, or ${__project_name} doesn't know how to configure it."
+        echo "Aborting."
+        exit 1
+      fi
       min_ver="v1.0.0"
-      extra_msg="Ethrex always expires pre-merge history. This command will have no effect."
-      prune_marker="/var/lib/ethrex/minimal-node"
+      if [[ "${target}" = "pre-merge" ]]; then
+        extra_msg="Ethrex always expires pre-merge history. This command will have no effect."
+        prune_marker="/var/lib/ethrex/minimal-node"
+      else
+        extra_msg="To switch to ${target} expiry requires a full resync, which should take 16-24 hours.\nYou can use https://rescuenode.com to keep attesting during resync."
+        prune_marker=""
+      fi
       ;;
     *)
       echo "${__project_name} does not know how to prune pre-merge history on ${client:-MysteryClient},"
@@ -2921,7 +3106,7 @@ prune-history() {
       ;;
   esac
 
-  echo "Pruning pre-merge history requires ${client} ${min_ver} or later."
+  echo "${target} history expiry requires ${client} ${min_ver} or later."
   echo
   if [[ -n "${extra_msg:-}" ]]; then
     echo -e "${extra_msg}"
@@ -2939,7 +3124,7 @@ prune-history() {
       done
     fi
     var=EL_NODE_TYPE
-    EL_NODE_TYPE=pre-merge-expiry
+    EL_NODE_TYPE=${target}-expiry
     __update_value_in_env "${var}" "${!var}" "${__env_file}"
     __non_interactive=1
     resync-execution
@@ -2988,14 +3173,14 @@ prune-history() {
   fi
 
   var=EL_NODE_TYPE
-  EL_NODE_TYPE=pre-merge-expiry
+  EL_NODE_TYPE=${target}-expiry
   __update_value_in_env "${var}" "${!var}" "${__env_file}"
   echo
-  echo "Starting ${client} pre-merge history prune"
+  echo "Starting ${client} ${target} history prune"
   __docompose run --rm set-prune-marker "touch ${prune_marker}"
   restart execution
   echo
-  echo "Pre-merge history prune is running, you can observe it with \"${__me} logs -f execution\""
+  echo "${target} history prune is running, you can observe it with \"${__me} logs -f execution\""
   echo
   echo "When prune is done, ${client} will automatically start again."
   echo
@@ -5519,8 +5704,8 @@ __full_help() {
   echo "    stops the Besu execution client and prunes trie-logs."
   echo "  prune-reth [--non-interactive]"
   echo "    stops the Reth execution client and prunes its DB."
-  echo "  prune-history [--non-interactive]"
-  echo "    stops the execution client and prunes pre-merge history, if supported."
+  echo "  prune-history [--non-interactive] [--pre-merge|--pre-cancun|--rolling|--aggressive]"
+  echo "    stops the execution client and configures history expiry."
   echo "  prune-lighthouse [--non-interactive]"
   echo "    stops the Lighthouse consensus client and prunes state."
   echo "  repair-reth"
