Support Nethermind FlatDB (#2568)

diff --git a/ethd b/ethd
--- a/ethd
+++ b/ethd
@@ -5,7 +5,7 @@ set -Eeuo pipefail
 __project_name="Eth Docker"
 __app_name="Ethereum node"
 __sample_service="consensus"
-__min_env_version=56
+__min_env_version=57
 __target_pg=18
 __current_docker=29
 __docker_exe="docker"
@@ -2945,6 +2945,14 @@ prune-nethermind() {
   __get_value_from_env "${var}" "${__env_file}" "__value"
   if [[ "${__value}" = "archive" ]]; then
     echo "Nethermind is an archive node: Aborting."
+    exit 1
+  fi
+
+  # Check for FlatDB
+  var="NETHERMIND_FLATDB"
+  __get_value_from_env "${var}" "${__env_file}" "__value"
+  if [[ -n "${__value}" ]]; then
+    echo "Nethermind is configured for FlatDB, which need not and cannot be pruned. Aborting."
     exit 1
   fi
 
