Fix screen on macOS (#2874)

diff --git a/ethd b/ethd
--- a/ethd
+++ b/ethd
@@ -3910,16 +3910,16 @@ update() {
     set -x
   fi
 
-  if [[ ! "$OSTYPE" = "darwin"* ]]; then
 # Only one copy of update() should run per Eth Docker stack
-    script_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
-    uniq_id="${script_dir//\//_}"
+  script_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
+  uniq_id="${script_dir//\//_}"
+  if [[ ! "$OSTYPE" = "darwin"* ]]; then
     __lock_file="${uniq_id}_lock"
     ${__as_owner} touch "/tmp/${__lock_file}"
     exec 200<"/tmp/${__lock_file}"
     if ! flock -n 200; then
-        echo "Another instance of \"${__me} update\" is running. Aborting."
-        exit 1
+      echo "Another instance of \"${__me} update\" is running. Aborting."
+      exit 1
     fi
   fi
 
